### ISSUE TITLE
I18n options

### ISSUE THREAD

**Issue by riccardo-forina** [syndesisio/syndesis-react-poc#8]
We should decide now that we are fresh how we are going to address i18n and l10n.

In the past I have had some success with [i18next](https://github.com/i18next/react-i18next). It’s actively maintained; just the other day they showed how to use it with React’s hooks.

**Comment by elvisisking** [comment]
Yes let's get this going now! Seems like the two most popular libraries are [react-intl and react-i18next](https://www.npmtrends.com/react-i18n-vs-react-i18next-vs-react-i18nify-vs-react-intl-vs-react-intl-redux). Should we start by looking into `react-i18next` since it has worked for @riccardo-forina in the past? [Here](https://www.i18next.com/overview/comparison-to-others) are some obviously biased reasons for using it versus other libraries. I can start implementing and documenting a potential solution. Wdyt?

**Comment by riccardo-forina** [comment]
I used also react-intl. It’s good but I’m not sure about the future of the project... it’s still under Yahoo name, but are they still active and doing stuff?

**Comment by gashcrumb** [comment]
I think this is done now, isn't it @elvisisking?

**Comment by elvisisking** [comment]
Yes @gashcrumb, I think this issue can be closed. If we run into any i18n-related issues going forward we can open up specific issues.
